name: reviewsvanklanten
recipe: laravel
config:
  webroot: public
  php: 7.3
  xdebug: false

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  phpmyadmin:
    type: phpmyadmin
    portforward: true

proxy:
  phpmyadmin:
    - pma-reviewsvanklanten.lndo.site
    - phpmyadmin-reviewsvanklanten.lndo.site

  mailhog:
    - hog-reviewsvanklanten.lndo.site
    - mailhog-reviewsvanklanten.lndo.site
