<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateBasicTables extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::create('companies', static function (Blueprint $table) {
            $table->id();
                $table->string('name');
                $table->string('uuid')->unique()->comment('autogenerated');
                $table->longText('description')->nullable();
            $table->timestamps();
        });

        Schema::create('properties', static function (Blueprint $table) {
            $table->id();
                $table->string('name');
                $table->longText('description')->nullable();
                $table->string('uuid')->unique()->comment('autogenerated');
                $table->unsignedBigInteger('parent_id')->nullable();
                $table->string('parent_type')->nullable();
            $table->timestamps();
        });

        Schema::create('reviews', static function (Blueprint $table) {
            $table->id();
                $table->string('name')->nullable();
                $table->string('uuid')->unique()->comment('autogenerated');
                $table->unsignedBigInteger('reviewable_id');
                $table->string('reviewable_type');
                $table->float('score', 4,2);
                $table->longText('remarks')->nullable();
                $table->string('email');
                $table->string('status')->default('on-hold');
            $table->timestamps();
        });

        Schema::create('comments', static function (Blueprint  $table) {
            $table->id();
                $table->unsignedBigInteger('user_id');
                $table->unsignedBigInteger('review_id');

            $table->timestamps();
        });

        Schema::create('company_user', static function (Blueprint $table) {
            $table->unsignedBigInteger('company_id');
            $table->unsignedBigInteger('user_id');

            $table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();
            $table->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        Schema::dropIfExists('companies');
        Schema::dropIfExists('properties');
        Schema::dropIfExists('reviews');
        Schema::dropIfExists('companies_users');
    }
}
