name: CI

on:
  push:
    branches:
      - 'releases/*'

jobs:
  deployment:
    name: "Deploy project to PRODUCTION"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: musps/action-deployer-php@master
        with:
          args: deploy production
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
